import { useState, useRef, useEffect } from 'react';
import { Plus, Minus, X, ChevronDown, Search, ShoppingCart, Check, Download } from 'lucide-react';
import {
  DAYS,
  MAX_MEALS_PER_DAY,
  PLANNER_ADD_TYPE as ADD_TYPE,
  PLANNER_MOVE_TYPE as MOVE_TYPE,
  usePlanner,
  type RecipeData,
} from './usePlanner';

interface Props {
  recipes: RecipeData[];
  basePath: string;
}

const EYEBROW: React.CSSProperties = {
  fontFamily: "'EB Garamond', Georgia, serif",
  fontWeight: 600,
  fontSize: 'var(--text-eyebrow)',
  textTransform: 'uppercase',
  letterSpacing: '0.24em',
  color: 'var(--color-oxblood)',
  margin: 0,
};

const HAIRLINE: React.CSSProperties = {
  border: 'none',
  borderTop: '1px solid var(--color-hairline)',
  margin: 0,
};

export function MealPlannerIsland({ recipes, basePath }: Props) {
  const {
    meals,
    shoppingList,
    listReady,
    loaded,
    grouped,
    checkedCount,
    canGenerate,
    selectRecipe,
    addCustom,
    removeMeal,
    moveMeal,
    updateServings,
    generateList,
    toggleItem,
    downloadList,
  } = usePlanner();

  const [openDay, setOpenDay] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [customInputs, setCustomInputs] = useState<Partial<Record<string, string>>>({});
  // Tap-to-move (touch + keyboard path): an armed meal awaits a destination day
  const [armedMeal, setArmedMeal] = useState<{ day: string; mealId: string } | null>(null);
  const [dragOverDay, setDragOverDay] = useState<string | null>(null);
  const shoppingRef = useRef<HTMLDivElement>(null);

  const isFull = (day: string) => (meals[day]?.length ?? 0) >= MAX_MEALS_PER_DAY;

  function toggleArm(day: string, mealId: string) {
    setArmedMeal((prev) => (prev?.mealId === mealId ? null : { day, mealId }));
  }

  function moveArmedTo(day: string) {
    if (!armedMeal) return;
    if (day !== armedMeal.day && !isFull(day)) {
      moveMeal(armedMeal.day, armedMeal.mealId, day);
    }
    setArmedMeal(null);
  }

  function handleChipDragStart(e: React.DragEvent, day: string, mealId: string) {
    e.dataTransfer.setData(MOVE_TYPE, JSON.stringify({ kind: 'move', fromDay: day, mealId }));
    e.dataTransfer.effectAllowed = 'move';
  }

  function handleDayDragOver(e: React.DragEvent, day: string) {
    // Full day = blocked: no preventDefault → no-drop cursor, no highlight
    if (isFull(day)) return;
    e.preventDefault();
    e.dataTransfer.dropEffect = e.dataTransfer.types.includes(MOVE_TYPE) ? 'move' : 'copy';
    setDragOverDay(day);
  }

  function handleDayDragLeave(e: React.DragEvent) {
    if (!(e.currentTarget as HTMLElement).contains(e.relatedTarget as Node)) {
      setDragOverDay(null);
    }
  }

  function handleDayDrop(e: React.DragEvent, day: string) {
    e.preventDefault();
    const moveRaw = e.dataTransfer.getData(MOVE_TYPE);
    if (moveRaw) {
      try {
        const { fromDay, mealId } = JSON.parse(moveRaw);
        moveMeal(fromDay, mealId, day);
      } catch {}
    } else {
      const addRaw = e.dataTransfer.getData(ADD_TYPE);
      if (addRaw) {
        try {
          const { recipeId } = JSON.parse(addRaw);
          const recipe = recipes.find((r) => r.id === recipeId);
          if (recipe) selectRecipe(day, recipe);
        } catch {}
      }
    }
    setDragOverDay(null);
  }

  // Auto-generate shopping list on mount if a week is already stored
  const hasAutoGenerated = useRef(false);
  useEffect(() => {
    if (loaded && canGenerate && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      generateList();
    }
  }, [loaded, canGenerate]); // eslint-disable-line react-hooks/exhaustive-deps

  const filtered = recipes.filter(
    (r) =>
      r.title.toLowerCase().includes(search.toLowerCase()) ||
      r.cuisine.toLowerCase().includes(search.toLowerCase())
  );

  function handleSelectRecipe(day: string, recipe: RecipeData) {
    if (!selectRecipe(day, recipe)) return; // day full
    setOpenDay(null);
    setSearch('');
  }

  function handleAddCustom(day: string) {
    addCustom(day, customInputs[day] ?? '');
    setCustomInputs((prev) => ({ ...prev, [day]: '' }));
    setOpenDay(null);
  }

  function handleGenerateList() {
    generateList();
    setTimeout(() => shoppingRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 100);
  }

  return (
    // Tap anywhere outside a chip/day target disarms tap-to-move
    <div style={{ backgroundColor: 'var(--color-paper)', minHeight: '60vh' }} onClick={() => setArmedMeal(null)}>
      <div style={{ maxWidth: '680px', margin: '0 auto', padding: 'var(--space-2xl) var(--space-lg)' }}>

        {/* Page header */}
        <div style={{ marginBottom: 'var(--space-2xl)' }}>
          <p style={{ ...EYEBROW, marginBottom: 'var(--space-xs)' }}>Plan</p>
          <h1 style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-title)', fontWeight: 500, color: 'var(--color-ink)', margin: '0 0 var(--space-2xs)' }}>
            Weekly Menu
          </h1>
          <p style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-meta)', color: 'var(--color-ink-muted)', margin: 0 }}>
            Pick meals for the week and generate a shopping list automatically.
          </p>
        </div>

        {/* Day rows */}
        <div style={{ borderBottom: '1px solid var(--color-hairline)', marginBottom: 'var(--space-xl)' }}>
          {DAYS.map((day) => {
            const dayMeals = meals[day] ?? [];
            const isOpen = openDay === day;
            const dayFull = isFull(day);
            const isMoveTarget = armedMeal !== null && armedMeal.day !== day && !dayFull;
            const isDragTarget = dragOverDay === day;

            return (
              <div key={day} style={{ borderTop: '1px solid var(--color-hairline)' }}>
                {/* Row: up to 4 meal chips + add; drop / tap-move target */}
                <div
                  onDragOver={(e) => handleDayDragOver(e, day)}
                  onDragLeave={handleDayDragLeave}
                  onDrop={(e) => handleDayDrop(e, day)}
                  onClick={isMoveTarget ? () => moveArmedTo(day) : undefined}
                  style={{
                    display: 'flex', alignItems: 'flex-start', gap: '12px', padding: 'var(--space-md) 0',
                    cursor: isMoveTarget ? 'pointer' : undefined,
                    background: isDragTarget ? 'rgba(126,38,37,0.06)' : undefined,
                    outline: isDragTarget ? '1px solid rgba(126,38,37,0.3)' : undefined,
                    transition: 'background 0.12s',
                  }}
                >
                  <span style={{ width: '88px', flexShrink: 0, marginTop: '7px', fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-eyebrow)', textTransform: 'uppercase', letterSpacing: '0.1em', color: 'var(--color-ink-muted)' }}>
                    {day}
                  </span>

                  <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: '8px' }}>
                    {dayMeals.map((meal) => {
                      const isArmed = armedMeal?.mealId === meal.id;
                      return (
                        <div
                          key={meal.id}
                          draggable
                          onDragStart={(e) => handleChipDragStart(e, day, meal.id)}
                          onClick={(e) => { e.stopPropagation(); toggleArm(day, meal.id); }}
                          onKeyDown={(e) => {
                            if (e.key === 'Enter' || e.key === ' ') {
                              e.preventDefault();
                              e.stopPropagation();
                              toggleArm(day, meal.id);
                            }
                          }}
                          tabIndex={0}
                          role="button"
                          aria-pressed={isArmed}
                          aria-label={`${meal.title} — ${isArmed ? 'tap a day to move it' : 'select to move'}`}
                          style={{
                            display: 'flex', alignItems: 'center', gap: '10px',
                            cursor: 'grab',
                            background: isArmed ? 'rgba(126,38,37,0.04)' : undefined,
                            outline: isArmed ? '1px solid rgba(126,38,37,0.3)' : undefined,
                            padding: '2px 4px', margin: '-2px -4px',
                          }}
                        >
                          {meal.image && (
                            <img
                              src={`${basePath}${meal.image}`}
                              alt=""
                              style={{ width: '32px', height: '32px', borderRadius: 'var(--radius-sm)', objectFit: 'cover', flexShrink: 0 }}
                            />
                          )}
                          <span style={{ flex: 1, fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-body)', color: isArmed ? 'var(--color-oxblood)' : 'var(--color-ink)' }}>{meal.title}</span>
                          {meal.recipeId === null && (
                            <span style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-eyebrow)', textTransform: 'uppercase', letterSpacing: '0.15em', color: 'var(--color-ink-muted)', border: '1px solid var(--color-hairline)', padding: '1px 6px' }}>
                              custom
                            </span>
                          )}
                          {/* Servings stepper — recipe meals only, bounds 1–12 */}
                          {meal.baseServings !== null && meal.servings !== null && (
                            <span
                              onClick={(e) => e.stopPropagation()}
                              style={{ display: 'flex', alignItems: 'center', gap: '6px', flexShrink: 0 }}
                            >
                              <button
                                onClick={() => updateServings(day, meal.id, (meal.servings ?? 1) - 1)}
                                disabled={(meal.servings ?? 1) <= 1}
                                aria-label={`Fewer servings for ${meal.title}`}
                                style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--color-oxblood)', padding: '2px', display: 'flex', lineHeight: 1, opacity: (meal.servings ?? 1) <= 1 ? 0.3 : 1 }}
                              >
                                <Minus size={12} />
                              </button>
                              <span className="onum" style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-meta)', minWidth: '1.5ch', textAlign: 'center', color: 'var(--color-ink)' }}>
                                {meal.servings}
                              </span>
                              <button
                                onClick={() => updateServings(day, meal.id, (meal.servings ?? 1) + 1)}
                                disabled={(meal.servings ?? 1) >= 12}
                                aria-label={`More servings for ${meal.title}`}
                                style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--color-oxblood)', padding: '2px', display: 'flex', lineHeight: 1, opacity: (meal.servings ?? 1) >= 12 ? 0.3 : 1 }}
                              >
                                <Plus size={12} />
                              </button>
                            </span>
                          )}
                          <button
                            onClick={(e) => { e.stopPropagation(); removeMeal(day, meal.id); }}
                            title={`Remove ${meal.title}`}
                            style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--color-ink-muted)', padding: '2px', display: 'flex', opacity: 0.6 }}
                          >
                            <X size={15} />
                          </button>
                        </div>
                      );
                    })}

                    {isMoveTarget && (
                      <button
                        onClick={(e) => { e.stopPropagation(); moveArmedTo(day); }}
                        style={{ alignSelf: 'flex-start', background: 'none', border: 'none', cursor: 'pointer', padding: 0, fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-meta)', fontStyle: 'italic', color: 'var(--color-oxblood)' }}
                      >
                        Move here…
                      </button>
                    )}

                    {!dayFull ? (
                      <button
                        onClick={(e) => { e.stopPropagation(); setOpenDay(isOpen ? null : day); }}
                        style={{ display: 'flex', alignItems: 'center', gap: '8px', background: 'none', border: 'none', cursor: 'pointer', color: 'var(--color-ink-muted)', fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-meta)', padding: 0 }}
                      >
                        <Plus size={14} />
                        <span>Add a meal</span>
                        <ChevronDown
                          size={14}
                          style={{ marginLeft: 'auto', transform: isOpen ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s' }}
                        />
                      </button>
                    ) : (
                      <span style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-meta)', color: 'var(--color-ink-muted)', fontStyle: 'italic' }}>
                        Day full ({MAX_MEALS_PER_DAY} meals)
                      </span>
                    )}
                  </div>
                </div>

                {/* Picker dropdown */}
                {isOpen && (
                  <div style={{ borderTop: '1px solid var(--color-hairline)', padding: 'var(--space-lg) 0' }}>
                    {/* Search */}
                    <div style={{ position: 'relative', marginBottom: 'var(--space-md)' }}>
                      <Search size={14} style={{ position: 'absolute', left: '10px', top: '50%', transform: 'translateY(-50%)', color: 'var(--color-ink-muted)' }} />
                      <input
                        type="text"
                        placeholder="Search recipes…"
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        style={{
                          width: '100%',
                          paddingLeft: '32px',
                          paddingRight: '12px',
                          paddingTop: '7px',
                          paddingBottom: '7px',
                          border: '1px solid var(--color-hairline)',
                          backgroundColor: 'var(--color-paper)',
                          color: 'var(--color-ink)',
                          fontFamily: "'EB Garamond', Georgia, serif",
                          fontSize: 'var(--text-meta)',
                          outline: 'none',
                          boxSizing: 'border-box',
                        }}
                      />
                    </div>

                    {/* Recipe grid */}
                    {filtered.length > 0 ? (
                      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(120px, 1fr))', gap: 'var(--space-xs)', marginBottom: 'var(--space-lg)' }}>
                        {filtered.map((r) => (
                          <button
                            key={r.id}
                            onClick={() => handleSelectRecipe(day, r)}
                            style={{
                              position: 'relative',
                              overflow: 'hidden',
                              aspectRatio: '3/2',
                              border: 'none',
                              cursor: 'pointer',
                              padding: 0,
                              backgroundColor: 'var(--color-stone)',
                            }}
                          >
                            {r.image ? (
                              <img
                                src={`${basePath}${r.image}`}
                                alt={r.title}
                                style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                              />
                            ) : (
                              <div style={{ width: '100%', height: '100%', backgroundColor: 'var(--color-stone)' }} />
                            )}
                            <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to top, rgba(0,0,0,0.65) 0%, transparent 55%)' }} />
                            <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, padding: '5px 7px', textAlign: 'left' }}>
                              <p style={{ color: 'white', fontSize: 'var(--text-eyebrow)', margin: 0, lineHeight: 1.3, fontFamily: "'EB Garamond', Georgia, serif" }}>{r.title}</p>
                            </div>
                          </button>
                        ))}
                      </div>
                    ) : (
                      <p style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-meta)', color: 'var(--color-ink-muted)', marginBottom: 'var(--space-md)', fontStyle: 'italic' }}>No recipes found.</p>
                    )}

                    {/* Custom name */}
                    <div>
                      <p style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-eyebrow)', color: 'var(--color-ink-muted)', marginBottom: 'var(--space-xs)' }}>
                        Or enter a custom dish:
                      </p>
                      <div style={{ display: 'flex', gap: 'var(--space-xs)' }}>
                        <input
                          type="text"
                          placeholder="Dish name…"
                          value={customInputs[day] ?? ''}
                          onChange={(e) => setCustomInputs((prev) => ({ ...prev, [day]: e.target.value }))}
                          onKeyDown={(e) => e.key === 'Enter' && handleAddCustom(day)}
                          style={{
                            flex: 1,
                            padding: '7px 10px',
                            border: '1px solid var(--color-hairline)',
                            backgroundColor: 'var(--color-paper)',
                            color: 'var(--color-ink)',
                            fontFamily: "'EB Garamond', Georgia, serif",
                            fontSize: 'var(--text-meta)',
                            outline: 'none',
                          }}
                        />
                        <button
                          onClick={() => handleAddCustom(day)}
                          disabled={!(customInputs[day] ?? '').trim()}
                          style={{
                            padding: '7px 16px',
                            border: 'none',
                            backgroundColor: 'var(--color-oxblood)',
                            color: 'var(--color-paper)',
                            fontFamily: "'EB Garamond', Georgia, serif",
                            fontSize: 'var(--text-meta)',
                            cursor: 'pointer',
                            opacity: (customInputs[day] ?? '').trim() ? 1 : 0.4,
                          }}
                        >
                          Add
                        </button>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Generate button */}
        <div style={{ marginBottom: 'var(--space-2xl)' }}>
          <button
            onClick={handleGenerateList}
            disabled={!canGenerate}
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '10px',
              padding: '10px 24px',
              border: canGenerate ? 'none' : '1px solid var(--color-hairline)',
              backgroundColor: canGenerate ? 'var(--color-oxblood)' : 'transparent',
              color: canGenerate ? 'var(--color-paper)' : 'var(--color-ink-muted)',
              fontFamily: "'EB Garamond', Georgia, serif",
              fontSize: 'var(--text-meta)',
              cursor: canGenerate ? 'pointer' : 'not-allowed',
              transition: 'opacity 0.15s',
            }}
          >
            <ShoppingCart size={16} />
            {listReady ? 'Update shopping list' : 'Generate shopping list'}
          </button>
          {!canGenerate && (
            <p style={{ fontFamily: "'EB Garamond', Georgia, serif", marginTop: 'var(--space-xs)', fontSize: 'var(--text-meta)', color: 'var(--color-ink-muted)', fontStyle: 'italic' }}>
              Add at least one meal to continue.
            </p>
          )}
        </div>

        {/* Shopping list */}
        {listReady && (
          <div ref={shoppingRef}>
            <div style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', marginBottom: 'var(--space-lg)' }}>
              <div>
                <p style={{ ...EYEBROW, marginBottom: 'var(--space-xs)' }}>Shopping list</p>
                <h2 style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-section)', fontWeight: 500, color: 'var(--color-ink)', margin: 0 }}>
                  Ingredients
                </h2>
              </div>
              <button
                onClick={downloadList}
                style={{
                  display: 'flex', alignItems: 'center', gap: '6px',
                  padding: '7px 14px',
                  border: '1px solid var(--color-hairline)',
                  backgroundColor: 'transparent',
                  color: 'var(--color-ink)',
                  fontFamily: "'EB Garamond', Georgia, serif",
                  fontSize: 'var(--text-meta)',
                  cursor: 'pointer',
                }}
              >
                <Download size={14} />
                Download
              </button>
            </div>

            {/* Progress */}
            {shoppingList.length > 0 && (
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: 'var(--space-xs) 0', borderTop: '1px solid var(--color-hairline)', borderBottom: '1px solid var(--color-hairline)', marginBottom: 'var(--space-lg)' }}>
                <span className="onum" style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-meta)', color: 'var(--color-ink-muted)' }}>
                  {checkedCount} of {shoppingList.length} checked
                </span>
                {checkedCount === shoppingList.length && shoppingList.length > 0 && (
                  <span style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-meta)', color: 'var(--color-olive)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                    <Check size={14} /> All done!
                  </span>
                )}
              </div>
            )}

            {shoppingList.length === 0 ? (
              <p style={{ fontFamily: "'EB Garamond', Georgia, serif", color: 'var(--color-ink-muted)', fontSize: 'var(--text-meta)', fontStyle: 'italic', padding: 'var(--space-lg) 0' }}>
                No ingredient data — all selected meals are custom.
              </p>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-xl)', paddingBottom: 'var(--space-3xl)' }}>
                {DAYS.filter((d) => grouped[d]).map((day) => (
                  <div key={day}>
                    {/* Day header */}
                    <div style={{ paddingBottom: 'var(--space-xs)', borderBottom: '1px solid var(--color-hairline)' }}>
                      <span style={{ ...EYEBROW }}>{day}</span>
                    </div>

                    {/* Meal blocks */}
                    {grouped[day].map(({ meal, sections }) => (
                      <div key={meal.id} style={{ marginTop: 'var(--space-sm)' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-sm)' }}>
                          <span style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-meta)', color: 'var(--color-ink)' }}>{meal.title}</span>
                          {meal.image && (
                            <img
                              src={`${basePath}${meal.image}`}
                              alt={meal.title}
                              style={{ width: '24px', height: '24px', borderRadius: 'var(--radius-sm)', objectFit: 'cover', marginLeft: 'auto' }}
                            />
                          )}
                        </div>

                        {/* Sections + items */}
                        {sections.map((sec, si) => (
                          <div key={si}>
                            {sec.header && (
                              <p style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-eyebrow)', textTransform: 'uppercase', letterSpacing: '0.15em', color: 'var(--color-ink-muted)', margin: 'var(--space-sm) 0 0', fontWeight: 600 }}>
                                {sec.header}
                              </p>
                            )}
                            {sec.items.map((item) => (
                              <label
                                key={item.id}
                                style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: 'var(--space-xs) 0', borderBottom: '1px solid var(--color-hairline)', cursor: 'pointer' }}
                              >
                                <span
                                  onClick={() => toggleItem(item.id)}
                                  style={{
                                    flexShrink: 0,
                                    width: '16px', height: '16px',
                                    border: item.checked ? 'none' : '1.5px solid var(--color-hairline)',
                                    backgroundColor: item.checked ? 'var(--color-oxblood)' : 'transparent',
                                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                                  }}
                                >
                                  {item.checked && <Check size={10} color="var(--color-paper)" />}
                                </span>
                                <span
                                  onClick={() => toggleItem(item.id)}
                                  className="onum"
                                  style={{
                                    fontFamily: "'EB Garamond', Georgia, serif",
                                    fontSize: 'var(--text-body)',
                                    color: item.checked ? 'var(--color-ink-muted)' : 'var(--color-ink)',
                                    textDecoration: item.checked ? 'line-through' : 'none',
                                    opacity: item.checked ? 0.55 : 1,
                                  }}
                                >
                                  {item.text}
                                </span>
                              </label>
                            ))}
                          </div>
                        ))}
                      </div>
                    ))}
                  </div>
                ))}

                {/* Note for custom meals */}
                {DAYS.some((d) => (meals[d] ?? []).some((m) => m.recipeId === null)) && (
                  <div style={{ borderTop: '1px solid var(--color-hairline)', paddingTop: 'var(--space-md)' }}>
                    <p style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-meta)', color: 'var(--color-ink-muted)', margin: '0 0 var(--space-xs)', fontStyle: 'italic' }}>
                      Custom meals (no ingredient data):
                    </p>
                    <ul style={{ margin: 0, paddingLeft: 'var(--space-md)' }}>
                      {DAYS.flatMap((d) =>
                        (meals[d] ?? [])
                          .filter((m) => m.recipeId === null)
                          .map((m) => (
                            <li key={m.id} style={{ fontFamily: "'EB Garamond', Georgia, serif", fontSize: 'var(--text-meta)', color: 'var(--color-ink-muted)', marginBottom: '2px' }}>
                              <span style={{ color: 'var(--color-ink)' }}>{d}:</span> {m.title}
                            </li>
                          ))
                      )}
                    </ul>
                  </div>
                )}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
